### PR TITLE
Agents forwarding

### PR DESCRIPTION
**Pull request by christian-pinto**
This pull request adds the logic that enables forwarding of requests from sunfish to the Hardware agents

### CODE REVIEW

**Review by rherrell — APPROVED** [review]
Looks good.  I appreciate the extra checks put in place to make the Sunfish Core Service more robust.  The assumptions about existing collections and new collections and whether they are tagged with the current Resource Aggregator or not might need to be revisited when we begin testing Agent 'Restarts'.  I haven't thought enough about such scenarios.

**Comment by christian-pinto** [comment]
> Looks good. I appreciate the extra checks put in place to make the Sunfish Core Service more robust. The assumptions about existing collections and new collections and whether they are tagged with the current Resource Aggregator or not might need to be revisited when we begin testing Agent 'Restarts'. I haven't thought enough about such scenarios.

Thanks @rherrell, yes the "Collections business" needs to be re-evaluated once we figure out the agents failover. At the moment when a new object is created invoking the external API, if the containing collection does not exist, we generate a warning but we create the collection as well.

**Comment by christian-pinto** [comment]
@mjaguil have you had a look at this PR?

**Review by mgazz — APPROVED** [review]
LGTM

**Pull request merged**
