### PR TITLE
Removed circular call where the core library calls itself instead of the plugins

### PR DESCRIPTION
**Pull request by christian-pinto**
…using plugins directly.

### CODE REVIEW

**Comment by christian-pinto** [comment]
@mjaguil @cayton Could you have a quick look at this PR?

**Comment by mjaguil** [comment]
Looking


From: Christian Pinto ***@***.***>
Date: Thursday, August 8, 2024 at 2:05 AM
To: OpenFabrics/sunfish_library_reference ***@***.***>
Cc: Aguilar, Michael James ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenFabrics/sunfish_library_reference] Removed circular call where the core library calls itself instead of the plugins (PR #32)

@mjaguil<https://github.com/mjaguil> @cayton<https://github.com/cayton> Could you have a quick look at this PR?

**Comment by mjaguil** [comment]
Nevermind….  Stupid 2-factor, I’ll have to get to it, later today

I can’t have my cell phone with me

From: Christian Pinto ***@***.***>
Date: Thursday, August 8, 2024 at 2:05 AM
To: OpenFabrics/sunfish_library_reference ***@***.***>
Cc: Aguilar, Michael James ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenFabrics/sunfish_library_reference] Removed circular call where the core library calls itself instead of the plugins (PR #32)

@mjaguil<https://github.com/mjaguil> @cayton<https://github.com/cayton> Could you have a quick look at this PR?

**Review by mjaguil — COMMENTED** [review]
advances in the interface calls to use the back-end storage library

**Review by mgazz — APPROVED** [review]

**Comment by christian-pinto** [comment]
> advances in the interface calls to use the back-end storage library

@mjaguil is the review approved? I can't really understand what this comment is about.

**Pull request merged**
